#!/bin/sh

# Application
APPLICATION_NAME=hello-world

# OCI Registry
REGION_CODE=phx			# e.g. iad, phx
REGION_NAME=us-phoenix-1        # e.g. us-ashburn-1, us-phoenix-1
TENANCY_NAME=

# OKE
NAMESPACE=default

# Provision OKE - only for provisioning OKE cluster
# If PROVISION_BASIC_CLUSTER is set to false, you are not required to enter the values below
PROVISION_BASIC_CLUSTER=false	# e.g. true, false
COMPARTMENT_OCID=
TENANCY_OCID=
USER_OCID=
USER_FINGERPRINT=
